version: "3.9"

services:
  metaroles:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - metaroles-network
    restart:
      always

networks:
  metaroles-network:
