version: "3.9"

services:
  metaroles:
    build:
      context: ./
      dockerfile: ./Dockerfile
    pull_policy: build
    environment:
      - PROJECT_NAME = Meta-Roles
      - LOAD_DEBUG_COMMANDS
      - DISCORD_TOKEN
      - SENTRY_DSN
    volumes:
      - logs:/app/logs
      - data:/app/data
    networks:
      - metaroles-network
    restart:
      always

networks:
  metaroles-network:

volumes:
  data:
    external: false
  logs:
    external: false
